provider:
  version: 0.2

routes:
  democom: 
    fqdn: demo.com
    routes:
      - name: api
        prefix: /api/assets
        redirect: www.demo.com
    includes:
      - namespace: other 
        name: api2
        prefix: /api/profile
        headers:
        - name: version
          op: equal
          values: v2

functions:
  assets_1:
    name: assets
    version: 0.1
    template: golang-http-handler
    annotations:
      example: eg
    build_args:
      LDFLAGS: "-w -s -extldflags '-static -pthread'"
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/assets
    routes:
      - name: api
        prefix: /api/assets

  assets_2:
    name: assets
    version: 0.2
    template: golang-http-handler
    annotations:
      example: eg
    build_args:
      LDFLAGS: "-w -s -extldflags '-static -pthread'"
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/assets
    routes:
      - name: api2
        prefix: /api/assets
        headers:
        - name: version
          op: exact
          value: v2

  profile:
    template: golang-http-handler
    version: 0.1
    annotations:
      example: eg
    env:
      EXAMPLE: eg
    envs:
      - .env/common
    secrets:
      - .secrets/profile
    routes:
      - name: api2
        prefix: /api/profile
        headers:
        - name: version
          op: equal
          values: v2