steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/contextcloud/ccb-cli:latest', '.']
  env:
  - 'VERSION=$REVISION_ID'
  - 'GIT_COMMIT=$SHORT_SHA'
images: 
- gcr.io/$PROJECT_ID/contextcloud/ccb-cli:latest