apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: {{ .Key }}
  namespace: {{ .Namespace }}
  labels: 
    commit: {{ .Commit | quote }}
spec:
  host: {{ .FQDN | quote }}
  upstreams:
{{- range $key, $value := .Upstreams }}
  - name: {{ $key }}
    service: {{ $key }}
    port: 8080
{{- end }}
  subroutes:
{{- range $key, $value := .Routes }}
  - path: {{ $value.Route.Prefix }}
    action:
      {{- if $value.Route.Redirect }}
      redirect:
        url: {{ $value.Route.Redirect }}
        code: 301
      {{- else }}
      pass: {{ $value.Key }}
      {{- end -}}
{{- end }}