apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Key }}
  namespace: {{ .Namespace }}
  labels: 
    commit: {{ .Commit | quote }}
spec:
  dnsNames:
  - {{ .FQDN | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Key }}