apiVersion: v1
kind: Service
metadata:
  name: {{ .Key }}
  namespace: {{ .Namespace }}
  labels: 
    release: {{ .Name }}
    version: {{ .Version | quote }}
{{- if $.Annotations }}
  annotations:
    {{- toYaml .Annotations | nindent 4 }}        
{{- end }}
spec:
  ports:
    - name: http
      port: 8080
    - name: metrics
      port: 8081
    - name: health
      port: 8082
  selector:
    release: {{ .Name }}
    version: {{ .Version | quote }}