apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels: 
    release: {{ .Name }}
spec:
  ports:
    - name: http
      port: 8080
    - name: metrics
      port: 8081
    - name: health
      port: 8082
  selector:
    release: {{ .Name }}