apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ .Key }}
  namespace: {{ .Namespace }}
  labels: 
    commit: {{ .Commit | quote }}
spec:
  virtualhost:
    fqdn: {{ .FQDN | quote }}
    tls:
      secretName: {{ .Key }}
{{- if $.Routes }}
  routes:
  {{- range $key, $value := .Routes }}
    - conditions:
      - prefix: {{ $value.Prefix }}
    {{- if $value.Headers }}
      {{- range $key, $value := $value.Headers }}
      - header:
          name: {{ $value.Name }}
      {{- end }}
    {{- end }}
    {{- if $value.Redirect }}
      requestRedirectPolicy:
        hostname: {{ $value.Redirect }}
    {{- else }}
      services:
        - name: {{ $value.Key }}
          port: 8080
    {{- end }}    
  {{- end }}
{{- end }}
{{- if .Includes }}
  includes:
  {{- range $key, $value := .Includes }}
    - conditions:
      - prefix: {{ $value.Prefix }}
    {{- if $value.Headers }}
      {{- range $key, $value := $value.Headers }}
      - header:
          name: {{ $value.Name }}
      {{- end }}
    {{- end }}
      name: {{ $value.Name | route }}
    {{- if $.Namespace }}
      namespace: {{ .Namespace | namespace }}
    {{- end }}
  {{- end }}
{{- end }}